name: dart_application_4
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  mongo_dart: ^0.10.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
